/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/storage/{storageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 세부적인 저장고 조회 */
        get: operations["findOne"];
        /** 저장고 수정 */
        put: operations["update"];
        post?: never;
        /** 저장고 삭제 */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 농가 정보 입력 */
        post: operations["saveProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 구글 로그인 */
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전체 저장고 조회 */
        get: operations["findAll"];
        put?: never;
        /** 저장고 등록 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{storageId}/quality-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 사진 기반 AI 사과 품질 판정 */
        post: operations["checkQuality"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{storageId}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMonthlySchedules"];
        put?: never;
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자 정보 조회 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{storageId}/major-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMajorSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 저장고 이름 목록 조회 (드롭다운용) */
        get: operations["myStorageNames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 선택 가능한 도매시장·품종 목록 */
        get: operations["options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 로그인 농가 정보 기반 맞춤 시세 예측 */
        get: operations["myForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/price/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 특정 도매시장·품종의 최근 시세 + 향후 7일 예측 */
        get: operations["forecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 시장가격 대시보드 조회 */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price-predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StorageRequest: {
            name: string;
            appleType: string;
            /** Format: date-time */
            storeDate: string;
            storageMethod: string;
            /** Format: int32 */
            brix?: number;
            /** Format: int32 */
            hardness?: number;
            condition: string;
            /** Format: int32 */
            amount?: number;
            preferredDate: string;
        };
        ApiResult: {
            result?: string;
        };
        ProfileRequest: {
            farmLocation: string;
            variety: string;
            /** Format: int32 */
            farmSize?: number;
            farmSizeUnit: string;
            shipmentType: string;
        };
        GoogleLoginRequest: {
            idToken: string;
        };
        LoginResponse: {
            accessToken?: string;
            isNewUser?: boolean;
        };
        QualityCheckResponse: {
            /** Format: int64 */
            storageId?: number;
            /** Format: date-time */
            checkedAt?: string;
            grade?: string;
            ripeness?: string;
            colorDescription?: string;
            shipmentComment?: string;
            confidence?: string;
            disclaimer?: string;
        };
        StorageDetailResponse: {
            /** Format: int64 */
            storageId?: number;
            name?: string;
            type?: string;
            /** Format: int32 */
            startDate?: number;
            /** Format: date-time */
            storeDate?: string;
            storageMethod?: string;
            /** Format: int32 */
            brix?: number;
            /** Format: int32 */
            hardness?: number;
            condition?: string;
            /** Format: int32 */
            amount?: number;
            preferredDate?: string;
            /** Format: int64 */
            storagePeriodDays?: number;
            /** Format: int32 */
            temperature?: number;
            /** Format: int32 */
            humidity?: number;
            /** Format: double */
            ethylene?: number;
            qualityStatus?: string;
            shipmentRecommendation?: string;
            analysisReason?: string;
            nearbyDates?: number[];
            qualityGrade?: string;
            qualityRipeness?: string;
            qualityColorDescription?: string;
            qualityShipmentComment?: string;
            qualityConfidence?: string;
            /** Format: date-time */
            qualityCheckedAt?: string;
        };
        ScheduleRequest: {
            title: string;
            /** Format: date */
            scheduleDate: string;
        };
        UserMeResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        StorageSummaryResponse: {
            /** Format: int64 */
            storageId?: number;
            name?: string;
            /** Format: int32 */
            startDate?: number;
            type?: string;
            storageMethod?: string;
            /** Format: int32 */
            brix?: number;
            /** Format: date */
            analysisStartDate?: string;
            /** Format: int64 */
            storagePeriodDays?: number;
        };
        MajorScheduleResponse: {
            title?: string;
            /** Format: date */
            date?: string;
            eventType?: string;
        };
        PriceOptionsResponse: {
            markets?: string[];
            varieties?: string[];
        };
        ForecastPoint: {
            date?: string;
            /** Format: int32 */
            price?: number;
            /** Format: int32 */
            low?: number;
            /** Format: int32 */
            high?: number;
            /** Format: int32 */
            horizon?: number;
        };
        ForecastResponse: {
            market?: string;
            variety?: string;
            matchedBy?: string;
            unit?: string;
            asOf?: string;
            generatedAt?: string;
            history?: components["schemas"]["HistoryPoint"][];
            forecast?: components["schemas"]["ForecastPoint"][];
        };
        HistoryPoint: {
            date?: string;
            /** Format: int32 */
            price?: number;
        };
        ScheduleResponse: {
            /** Format: int64 */
            scheduleId?: number;
            title?: string;
            /** Format: date */
            scheduleDate?: string;
        };
        AiMarketAnalysis: {
            title?: string;
            report_text?: string;
        };
        ChartData: {
            date?: string;
            /** Format: int32 */
            price?: number;
        };
        CurrentPriceInfo: {
            /** Format: int32 */
            price_per_kg?: number;
            currency?: string;
            /** Format: double */
            change_rate?: number;
            change_direction?: string;
        };
        PriceDashboardResponse: {
            status?: string;
            search_info?: components["schemas"]["SearchInfo"];
            current_price_info?: components["schemas"]["CurrentPriceInfo"];
            price_summary?: components["schemas"]["PriceSummary"];
            chart_data?: components["schemas"]["ChartData"][];
            ai_market_analysis?: components["schemas"]["AiMarketAnalysis"];
        };
        PriceSummary: {
            /** Format: int32 */
            today_price?: number;
            today_basis_date?: string;
            /** Format: int32 */
            weekly_average_price?: number;
            weekly_basis_range?: string;
            /** Format: int32 */
            monthly_average_price?: number;
            monthly_basis_range?: string;
        };
        SearchInfo: {
            formatted_title?: string;
            date?: string;
            market?: string;
            item?: string;
            variety?: string;
        };
        PricePredictionChartPoint: {
            /** Format: date */
            date?: string;
            /** Format: int32 */
            predictedPrice?: number;
            /** Format: int32 */
            actualPrice?: number;
        };
        PricePredictionHistoryResponse: {
            chartPoints?: components["schemas"]["PricePredictionChartPoint"][];
            tableRows?: components["schemas"]["PricePredictionTableRow"][];
        };
        PricePredictionTableRow: {
            /** Format: date */
            date?: string;
            /** Format: int32 */
            predictedPrice?: number;
            /** Format: int32 */
            actualPrice?: number;
            /** Format: double */
            changeRate?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StorageDetailResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResult"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResult"];
                };
            };
        };
    };
    saveProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResult"];
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StorageSummaryResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResult"];
                };
            };
        };
    };
    checkQuality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QualityCheckResponse"];
                };
            };
        };
    };
    startAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StorageDetailResponse"];
                };
            };
        };
    };
    getMonthlySchedules: {
        parameters: {
            query: {
                year: number;
                month: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponse"][];
                };
            };
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    getMajorSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MajorScheduleResponse"][];
                };
            };
        };
    };
    myStorageNames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceOptionsResponse"];
                };
            };
        };
    };
    myForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ForecastResponse"];
                };
            };
        };
    };
    forecast: {
        parameters: {
            query: {
                market: string;
                variety: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ForecastResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query: {
                date: string;
                market_code: string;
                item_code: string;
                variety_code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceDashboardResponse"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query: {
                cropType: string;
                period?: "ONE_MONTH" | "SIX_MONTHS" | "ONE_YEAR";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PricePredictionHistoryResponse"];
                };
            };
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
